# name: AntiFlood
# version: 1.1
# author: VisMUT
# Mc-Nova 03.06.2019
Configuration:
  # Интервал между сообщениями игрока (с)
  time: 3
  prefix: "&c[&6MC-Nova&c]&6:"
  message: "Вы пишите в чат слишком часто!"
  no_permission: "Недостаточно прав."
# Режим совместимости с плагином UltimateChat
UltimateChat_Compatibility:
  enable: true
  channels: "!;*;?;%"
